version: "3"

services:  
  privatenode:
    build: .
    image: privatenode
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
    stop_signal: SIGINT
    stop_grace_period: 2m     
    command:
      - --ipcdisable            
      - --http
      - --http.api
      - "eth,net,web3"
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api
      - "eth,net,web3"
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
      - --datadir
      - "/chaindata"
      - --mine
      - --miner.threads=1
      - --miner.gastarget
      - "0xE0000000"
      - --miner.gaslimit
      - "0xE0000000"      
      - --rpc.gascap
      - "0xE0000000"
      - --rpc.evmtimeout
      - "0"
      - --verbosity
      - "4"      
      - --nousb
      # Minimum number of executable transaction slots guaranteed per account (default: 16)
      # - --txpool.accountslots=16
      # Maximum number of non-executable transaction slots for all accounts (default: 1024)
      # --txpool.globalqueue=1024
      # Maximum number of executable transaction slots for all accounts (default: 4096)
      # - --txpool.globalslots=10000
      # Maximum amount of time non-executable transaction are queued (default: 3h0m0s)
      # - --txpool.lifetime=3h0m0s
      # Megabytes of memory allocated to internal caching (default: 1024)
      # - --cache=4096
      # Maximum number of network peers (network disabled if set to 0) (default: 25)
      - --maxpeers=0
      # Blockchain sync mode ("fast", "full", or "light")
      - --syncmode=full
      # Blockchain garbage collection mode ("full", "archive") (default: "full")
      # - --gcmode=full 
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"